substitutions:
  devicename: utility
  upper_devicename: "Utility"
  board: nodemcuv2
  device_ip: "192.168.1.217"

<<: !include templatefiles/esp32.yaml

remote_receiver:
  pin:
    number: GPIO32
    inverted: False
  dump:
    - rc5
    - samsung
    - lg
    - nec
    - panasonic
    - jvc
    - sony
    - rc_switch
