substitutions:
  devicename: utility
  upper_devicename: "Utility"
  device_ip: "192.168.1.217"

<<: !include templatefiles/esp32.yaml

remote_receiver:
  pin:
    number: GPIO32
    inverted: False
  dump:
    #- rc5
    #- samsung
    #- lg
    #- nec
    #- panasonic
    #- jvc
    #- sony
    - rc_switch
    #- raw
  tolerance: 50%
  filter: 2us
  idle: 2ms
binary_sensor:
  - platform: remote_receiver
    name: "Back Door Low Battery"
    id: backdoor_battery
    rc_switch_raw:
      protocol: 1
      code: '1'
  - platform: template
    id: backdoortamper
    name: "Back Door Tamper Sensor"
    filters: []
    device_class: door
  - platform: remote_receiver
    name: "Back Door Tamper"
    id: backdoor_tamper
    internal: true
    rc_switch_raw:
      protocol: 1
      code: '101100001010101000000111'
    on_press:
      if:
        condition:
          - binary_sensor.is_off: backdoortamper
        then:
          - binary_sensor.template.publish:
              id: backdoortamper
              state: ON
  - platform: template
    id: backdoor
    name: "Back Door Sensor"
    filters: []
    device_class: door
  - platform: remote_receiver
    name: "Back Door Open"
    id: backdoor_open
    internal: true
    rc_switch_raw:
      protocol: 1
      code: '101100001010101000001010'
    on_press:
      if:
        condition:
          - binary_sensor.is_off: backdoor
        then:
          - binary_sensor.template.publish:
              id: backdoor
              state: ON
  - platform: remote_receiver
    name: "Back Door Closed"
    id: backdoor_closed
    internal: true
    rc_switch_raw:
      protocol: 1
      code: '101100001010101000001110'
    on_press:
      if:
        condition:
          - binary_sensor.is_on: backdoor
        then:
          - binary_sensor.template.publish:
              id: backdoor
              state: OFF
  - platform: remote_receiver
    name: "Front Door Low Battery"
    id: frontdoor_battery
    rc_switch_raw:
      protocol: 1
      code: '1'
  - platform: template
    id: frontdoortamper
    name: "Front Door Tamper Sensor"
    filters: []
    device_class: door
  - platform: remote_receiver
    name: "Front Door Tamper"
    id: frontdoor_tamper
    internal: true
    rc_switch_raw:
      protocol: 1
      code: '110110010111110100000111'
    on_press:
      if:
        condition:
          - binary_sensor.is_off: frontdoortamper
        then:
          - binary_sensor.template.publish:
              id: frontdoortamper
              state: ON
  - platform: template
    id: frontdoor
    name: "Front Door Sensor"
    filters: []
    device_class: door
  - platform: remote_receiver
    name: "Front Door Open"
    id: frontdoor_open
    internal: true
    rc_switch_raw:
      protocol: 1
      code: '110110010111110100001010'
    on_press:
      if:
        condition:
          - binary_sensor.is_off: frontdoor
        then:
          - binary_sensor.template.publish:
              id: frontdoor
              state: ON
  - platform: remote_receiver
    name: "Front Door Closed"
    id: frontdoor_closed
    internal: true
    rc_switch_raw:
      protocol: 1
      code: '110110010111110100001110'
    on_press:
      if:
        condition:
          - binary_sensor.is_on: frontdoor
        then:
          - binary_sensor.template.publish:
              id: frontdoor
              state: OFF
