esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

#deep_sleep:
#  run_duration: 5s
#  sleep_duration: 60min

uart:
  rx_pin: RX
  baud_rate: 4800

<<: !include common_static.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${upper_devicename} Button
    on_press:
      - switch.toggle: fakebutton
  - platform: template
    name: ${upper_devicename} Running
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    id: ${devicename}_wifi_signal
    update_interval: 900s
  - platform: uptime
    name: ${upper_devicename} Uptime
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 2s
    current:
      name: ${upper_devicename} Current
    voltage:
      name: ${upper_devicename} Voltage
    power:
      name: ${upper_devicename} Power
      id: power
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: led
        - below: 3.0
          then:
            - light.turn_off: led
  - platform: total_daily_energy
    name: ${upper_devicename} Total Daily Energy
    power_id: power
switch:
  - platform: restart
    name:  ${upper_devicename} Restart
  - platform: template
    name: ${upper_devicename} Relay
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
    turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
  - platform: gpio
    id: relay
    pin: GPIO12

text_sensor:
  - platform: version
    name: ${upper_devicename} Version
  - platform: template
    name: ${upper_devicename} MAC Address
    lambda: 'return {WiFi.macAddress().c_str()};'
    icon: mdi:fingerprint
    update_interval: 60s
  - platform: template
    name: ${upper_devicename} Wifi Strength
    id: ${devicename}_wifi_strength
    icon: "mdi:wifi"
    lambda: |-
      if (id(${devicename}_wifi_signal).state > -50 ) {
        return {"Excellent"};
      } else if (id(${devicename}_wifi_signal).state > -60) {
        return {"Good"};
      } else if (id(${devicename}_wifi_signal).state > -70) {
        return {"Fair"};
      } else if (id(${devicename}_wifi_signal).state < -70) {
        return {"Weak"};
      } else {
        return {"None"};
      }
    update_interval: 900s

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO15
      inverted: True

light:
  - platform: monochromatic
    name: ${upper_devicename} Blue LED
    output: pow_blue_led
    id: led
